<% 
time = Time.now.to_i
screnshots_path = "screenshots-#{time}"
Dir.mkdir screnshots_path unless Dir.exist? screnshots_path
common = "SCREENSHOT_PATH=#{screnshots_path}/"
report = "report-#{time}.html" %>
default: <%= common %>
html: <%= common %> --format progress --format html --out <%= report %>
mbe: <%= common %> TESTDATA=mbe
device: <%= common %>  RESET_BETWEEN_SCENARIOS=1 SCREENSHOT_VIA_USB=true
htc_one_x: ADB_DEVICE_ARG=SH24VW101093 TEST_SERVER_PORT=15555 -p device -p html
galaxy_note: ADB_DEVICE_ARG=304D0E43D41CBD9F TEST_SERVER_PORT=15556 -p device -p html
nexus_s: ADB_DEVICE_ARG=3532536C459200EC TEST_SERVER_PORT=15557 -p device -p html
galaxy_s2_ics: ADB_DEVICE_ARG=00090e381bc54f TEST_SERVER_PORT=15557 -p device -p html