<% 
time = Time.now.to_i
screnshots_path = "screenshots-#{time}"
Dir.mkdir screnshots_path unless Dir.exist? screnshots_path
common = "SCREENSHOT_PATH=#{screnshots_path}/"
report = "report-#{time}.html" %>
default: <%= common %>
html: <%= common %> --format progress --format html --out <%= report %>
mbe: <%= common %> TESTDATA=mbe
device: <%= common %>  RESET_BETWEEN_SCENARIOS=1 SCREENSHOT_VIA_USB=true
# QA devices
dv02: ADB_DEVICE_ARG=SH24VW101093 TEST_SERVER_PORT=15550 -p device -p html
dv03: ADB_DEVICE_ARG=304D19A25F46958E TEST_SERVER_PORT=15554 -p device -p html
dv06: ADB_DEVICE_ARG=450704443C0B617 TEST_SERVER_PORT=15555 -p device -p html
dv10: ADB_DEVICE_ARG=3532536C459200EC TEST_SERVER_PORT=15552 -p device -p html
dv13: ADB_DEVICE_ARG=304D0E43D41CBD9F TEST_SERVER_PORT=15551 -p device -p html
dv14: ADB_DEVICE_ARG=00090e381bc54f TEST_SERVER_PORT=15553 -p device -p html
dv04: ADB_DEVICE_ARG=3735BBD89FD600EC TEST_SERVER_PORT=15556 -p device -p html
dv11: ADB_DEVICE_ARG=1000b07e2740 TEST_SERVER_PORT=15557 -p device -p html
dv09: ADB_DEVICE_ARG=HT99DL901369 TEST_SERVER_PORT=15558 -p device -p html